In [28]:
import numpy as np
import bounded_multivariate_SMM as smm
from sklearn import datasets
from scipy.spatial import distance

In [22]:
iris = datasets.load_iris()
x = iris.data[:6,:3]
cov = np.cov(x.T)
mean = np.mean(x, axis = 0)
print(cov)
z = np.random.normal(size = (10, cov.shape[0]))
s = z.dot(cov)+mean
print(s)

[[0.083      0.085      0.025     ]
 [0.085      0.11766667 0.029     ]
 [0.025      0.029      0.019     ]]
[[4.91549001 3.32263623 1.42390617]
 [4.96440782 3.39060437 1.4611226 ]
 [4.81408946 3.23197545 1.39446781]
 [5.00321825 3.44082948 1.47634589]
 [5.07208731 3.55167511 1.48279645]
 [4.80815784 3.23947916 1.41850394]
 [4.93652183 3.36104709 1.44753024]
 [4.98119644 3.3960749  1.45190744]
 [4.90211692 3.3467697  1.43762737]
 [4.98428284 3.40909287 1.44784961]]


In [26]:
up = np.amax(x, axis=0)
low = np.amin(x, axis=0)
ind = np.array([int(np.where(((xi < up).all() and (xi > low).all()), 1, 0)) for xi in s])
print(ind)

[1 1 1 1 1 1 1 1 1 1]


In [47]:
def h(xi, mu, sig):
    '''gamma weights for the bounded version of SMM'''
    d = xi.shape[0]
    numer = 10 + d
    mah = distance.mahalanobis(xi, mu, sig)
    denom = 10 + mah
    return numer / denom

In [30]:
s

array([[4.91549001, 3.32263623, 1.42390617],
       [4.96440782, 3.39060437, 1.4611226 ],
       [4.81408946, 3.23197545, 1.39446781],
       [5.00321825, 3.44082948, 1.47634589],
       [5.07208731, 3.55167511, 1.48279645],
       [4.80815784, 3.23947916, 1.41850394],
       [4.93652183, 3.36104709, 1.44753024],
       [4.98119644, 3.3960749 , 1.45190744],
       [4.90211692, 3.3467697 , 1.43762737],
       [4.98428284, 3.40909287, 1.44784961]])

In [31]:
s-mean

array([[-0.03450999, -0.06069711, -0.02609383],
       [ 0.01440782,  0.00727104,  0.0111226 ],
       [-0.13591054, -0.15135788, -0.05553219],
       [ 0.05321825,  0.05749614,  0.02634589],
       [ 0.12208731,  0.16834178,  0.03279645],
       [-0.14184216, -0.14385417, -0.03149606],
       [-0.01347817, -0.02228624, -0.00246976],
       [ 0.03119644,  0.01274157,  0.00190744],
       [-0.04788308, -0.03656364, -0.01237263],
       [ 0.03428284,  0.02575954, -0.00215039]])

In [39]:
np.matmul((s-mean).T,s-mean)

array([[0.06234987, 0.07011913, 0.01909325],
       [0.07011913, 0.08164448, 0.02211291],
       [0.01909325, 0.02211291, 0.00681758]])

In [44]:
((s-mean)**2).sum(axis = 0)

array([0.06234987, 0.08164448, 0.00681758])

In [48]:
h_s = np.array([h(xi,mean,cov) for xi in s])

In [49]:
h_s

array([1.29582458, 1.29902518, 1.28802116, 1.29530218, 1.28805063,
       1.2884195 , 1.29852198, 1.29829776, 1.29655981, 1.29768246])